workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux
    environment:
      groups:
        - keystore_credentials
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/outputs/apk/release/*.apk
